source 'https://api.berkshelf.com'
cookbook 'user'
cookbook 'sudo'
cookbook 'openssh'
cookbook 'yum'
cookbook 'simple_iptables'
cookbook 'ntp'
cookbook 'nginx'
cookbook 'php', git: 'git://github.com/priestjim/chef-php.git'
cookbook 'mysql'
cookbook 'database'
cookbook 'phpmyadmin'
#cookbook 'ya-piwik', git: 'git://github.com/sharkpp-cookbooks/ya-piwik.git'
cookbook 'ya-piwik', path: "../ya-piwik"
